### ISSUE TITLE
Track Development Phases for the Alarms Component

### ISSUE THREAD

**Issue by Beelzebot777** [Beelzebot777/Pelusa-FrontEnd-Strateger-Public#48]
### Building Cicle
- [x] Beelzebot777/Pelusa-FrontEnd-Strateger#73
- [x] Beelzebot777/Pelusa-FrontEnd-Strateger#74
- [x] Beelzebot777/Pelusa-FrontEnd-Strateger#75
- [x] Beelzebot777/Pelusa-FrontEnd-Strateger#76
- [x] Beelzebot777/Pelusa-FrontEnd-Strateger#77
- [x] Beelzebot777/Pelusa-FrontEnd-Strateger#78

### Consolidate Cicle
- [x] Beelzebot777/Pelusa-Docs-Public#24
- [x] Beelzebot777/Pelusa-FrontEnd-Strateger#80
- [x] Beelzebot777/Pelusa-FrontEnd-Strateger#81
