### ISSUE TITLE
Track Development Phases for the NavBar Component

### ISSUE THREAD

**Issue by Beelzebot777** [Beelzebot777/Pelusa-FrontEnd-Strateger-Public#51]
### Building Cicle
- [x] Beelzebot777/Pelusa-FrontEnd-Strateger-Public#86
- [x] Beelzebot777/Pelusa-FrontEnd-Strateger-Public#87
- [x] Beelzebot777/Pelusa-FrontEnd-Strateger-Public#88
- [x] Beelzebot777/Pelusa-FrontEnd-Strateger-Public#89
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger-Public#90
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger-Public#91

### Consolidate Cicle
- [x] Beelzebot777/Pelusa-Docs-Public#30
- [x] Beelzebot777/Pelusa-FrontEnd-Strateger-Public#93
- [x] Beelzebot777/Pelusa-FrontEnd-Strateger-Public#94
