### ISSUE TITLE
Track Development Phases for the Diary Component

### ISSUE THREAD

**Issue by Beelzebot777** [Beelzebot777/Pelusa-FrontEnd-Strateger-Public#61]
### Building Cicle
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger-Public#120
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger-Public#121
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger-Public#122
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger-Public#123
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger-Public#139
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger-Public#140

### Consolidate Cicle
- [ ] Beelzebot777/Pelusa-Docs-Public#34
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger-Public#142
- [ ] Beelzebot777/Pelusa-FrontEnd-Strateger-Public#143
